### ISSUE TITLE
Error: LinkedIn website changed

### ISSUE THREAD

**Issue by YuriMicheloni** [linkedtales/scrapedin#110]
Hey! 

First, sorry for my bad english. 

Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues

Tks.

**Comment by gautierdag** [comment]
Can you provide more information? Can you run with option `hasToLog: true` ? Do you have an example profile page where it breaks?

Are you using cookies? Have you tried headless on/off ? 

What does the browser interaction look like if not in headless? It should still be able to load the linkedin page.

**Comment by leonardiwagner** [comment]
@YuriMicheloni please also test new version v`1.0.19`

**Comment by YuriMicheloni** [comment]
Hey Guys, thanks! 
Is working now, I downloaded the new version, sorry for the inconvenience.
