### ISSUE TITLE
How to handle pin verification

### ISSUE THREAD

**Issue by awais786327** [linkedtales/scrapedin#128]
I made a new Linkedin account so I am not getting worried about blocking reason when running npm run server I am getting an email which saying someone just trying to log in please enter verification code I don't know where I have to put that code in my server please tell me bcz I did not turn on two-step verification process and one more thing it is working with my old account and I am not getting any verification email in that account

**Comment by awais786327** [comment]
@leonardiwagner what should I do now to make it work?

**Comment by gautierdag** [comment]
This library does not provide a way to solve for LinkedIn's security verification (or captcha solving ... etc). If you wish to implement a verification detection and solver, I am sure that it would be most welcomed as it is a recurring question :) !

Until then, it is recommended that you solve these steps yourselves and use cookies from your manual verification to continue scraping.

Fresh accounts will tend to be susceptible to LinkedIn's verification or captcha block as they try to prevent scraping accounts. To minimize down-time you should try to "warmup" your fresh account (gradually increase the number of profile you scrape), use same or similar IP address and user agent between calls, and phone-verify your account. Whatever you can think to make your account more real will likely decrease the verification block (hence why you never get it on your real account which is probably aged and verified).

**Comment by leonardiwagner** [comment]
@awais786327 Plus, there a guide to help you solve that manual check: https://github.com/linkedtales/scrapedin/wiki/Tips

**Comment by awais786327** [comment]
okay thank's I don't have much time to use manual check one last way what I left is to use my old account
