### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by IamBlueSlime** [linkedtales/scrapedin#158]
Hi,

Many PRs are not merged since quite some time. Also, critical issue are not taking into account, like #157 which fixes the parsing tags.

If you don't have the time anymore to maintain this project this is fine, no worries :) But will you be okay to add one or two new persons as maintainer on this repository to avoid having an "official community fork"?

For a work project, I've to use this library. To be fair we had used it 2 years ago but paused the project. Today I've 2 choices: (1) I fork the project under my GitHub organization and I try to merge the PRs of this repository (2) I rewrite this project from scratch directly in my project.

To be fair, Scrapdin is quite old and it would be nice to rewrite it in Typescript, etc. So, the question is: **what do you want your community to do?** 😃 

Thanks!

**Comment by leonardiwagner** [comment]
Hi @IamBlueSlime it's not "dead" but there are no many active maintainers, are you willing to do that? I can add you as maintainers as well.

The hardest part for me is to test after PR is merged, I'm very busy lately, so I add anyone who's willing to do that.

**Comment by leonardiwagner** [comment]
I created an issue to add whoever that's willing to help: https://github.com/linkedtales/scrapedin/issues/160
