### ISSUE TITLE
Profile not found

### ISSUE THREAD

**Issue by ghazette** [linkedtales/scrapedin#23]
It's look like the css rules have changed, i tried to fix it but i haven't enough time.

ERROR:

### (node:21488) UnhandledPromiseRejectionWarning: Error: linkedin: profile not found

**Comment by leonardiwagner** [comment]
Hi @ghazette , could you inform what version are you using?

you could swap between `v1.0.5` and `v1.0.4` and tell me the results? thanks!

**Comment by CarlaFernandez** [comment]
Hi, I'm having the same problem with version `v1.0.5`, any updates? Thanks!

**Comment by leonardiwagner** [comment]
Hi @CarlaFernandez thanks for your feedback! I fixed that and published the version `v1.0.6`

Please let me know if it's working now, thanks

**Comment by CarlaFernandez** [comment]
It is working now, thanks a lot!

**Comment by ghazette** [comment]
Working like a charm !
Is it possible to scrap company description ?

**Comment by noushinquazi** [comment]
Hello, i just updated to `v1.0.7` but am encountering this issue:
```Error: linkedin: profile not found```

Below that error in the traceback is:
```UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined```

**Comment by leonardiwagner** [comment]
> Is it possible to scrap company description ?

@ghazette  where is that located? could you provide an example?

**Comment by leonardiwagner** [comment]
@noushinquazi could you provide a profile that throws this error?
