### ISSUE TITLE
Error: LinkedIn website changed and scrapedin can't read basic data

### ISSUE THREAD

**Issue by noushinquazi** [linkedtales/scrapedin#24]
ScrapedIn is able to open the profiles in browser but does not scrape or save anything.

**Comment by mmvcode** [comment]
`scrapedin: 2019-06-12T07:18:58.841Z info: [scrapedin] initializing
scrapedin: 2019-06-12T07:18:58.845Z info: [scrapedin] required parameters email and password was provided
Promise { <pending> }
scrapedin: 2019-06-12T07:19:00.106Z info: [login] logging at: https://www.linkedin.com/login
scrapedin: 2019-06-12T07:19:04.886Z info: [login] logged feed page selector found
[Function]
scrapedin: 2019-06-12T07:19:04.890Z info: [profile] starting scraping url: <omitted>
scrapedin: 2019-06-12T07:19:09.267Z info: [profile] scrolling page to the bottom
scrapedin: 2019-06-12T07:19:09.770Z info: [scrollToPageBottom] scrolling to page bottom (1)
scrapedin: 2019-06-12T07:19:10.274Z info: [scrollToPageBottom] scrolling to page bottom (2)
scrapedin: 2019-06-12T07:19:10.371Z info: [profile] applying 1st delay
scrapedin: 2019-06-12T07:19:10.621Z info: [profile] clicking on see more buttons
scrapedin: 2019-06-12T07:19:10.790Z info: [profile] applying 2nd delay
scrapedin: 2019-06-12T07:19:11.159Z info: [profile] finished scraping url: <omitted>
scrapedin: 2019-06-12T07:19:11.159Z error: [cleanMessageData] LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
    at module.exports (/Users/mmvcode/sd/node_modules/scrapedin/src/cleanProfileData.js:7:11)
    at module.exports (/Users/mmvcode/sd/node_modules/scrapedin/src/profile.js:71:26)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)`

**Comment by mmvcode** [comment]
This seems to be happening due to the `profile` and `about` templates, the others work.

**Comment by leonardiwagner** [comment]
Thanks @mmvcode  and @noushinquazi for the report. It was fixed on `v1.0.7` please update your scrapedin version.

LinkedIn rolled back layout updates, so to avoid this ping-pong about legacy and new layout I managed to scrapedin accept both and see what's working, I hope in that way this problem is avoided in the future, details here: https://github.com/linkedtales/scrapedin/commit/81c41e35a605545d5749e509c6547fe112b2d826

**Comment by noushinquazi** [comment]
Thank you @leonardiwagner and @mmvcode for the speedy response! After upgrading scrapedin this particular issue did get resolved. However, scrapedin is now failing on some profiles for a different reason, which I can pull a separate issue for.

**Comment by leonardiwagner** [comment]
@noushinquazi please give me profile URLs where this error happens, thanks!

**Comment by leonardiwagner** [comment]
closing due to lack of information, please re-open if problem still occurs.
