### ISSUE TITLE
waitTimeMs not respected

### ISSUE THREAD

**Issue by christopherfrance** [linkedtales/scrapedin#28]
Seems like no matter what I set `waitTimeMs` to it is ignored and the recaptcha is closed before I can finish it — it shows me more than three recaptchas sometimes.

**Comment by leonardiwagner** [comment]
Hi @christopherfrance , could you provide the piece of code which you call `profileScraper`?

Also , at `scrapedin` function, please set `hasToLog` option to `true` so we can see two logs to ensure ẁaitTimeMs` is applied:
- applying 1st delay
- applying 2nd delay

**Comment by leonardiwagner** [comment]
closing due to lack of feedback
