### ISSUE TITLE
Login issue on server 

### ISSUE THREAD

**Issue by myvirtualteams** [linkedtales/scrapedin#30]
![image](https://user-images.githubusercontent.com/5236389/63004265-97585b00-be97-11e9-852f-36cc7b63871b.png)
Getting login issue on server but if I run this project on local then its working fine

**Comment by leonardiwagner** [comment]
> Manual check was required

This means LinkedIn is asking for a manual check: a recaptcha or asking to optionally add a phone number.

This is very common when you try to login at a new device. More details how to solve here: https://github.com/linkedtales/scrapedin/blob/master/README.md#tips
