### ISSUE TITLE
Falsy Company Name in positions coming as title

### ISSUE THREAD

**Issue by imnamanmodi1** [linkedtales/scrapedin#32]
When a LinkedIn user has multiple positions in same company, the company name scraped is correct but when the user just has one position in a company, the company name which gets scraped is the position of the user in the company

**Comment by Netgator** [comment]
I believe my current pull request also addresses this issue

**Comment by leonardiwagner** [comment]
fixed on `v1.0.9` release, just update your version, thank you, guys!
