### ISSUE TITLE
Company Name and Location are not being collected due to changes in css

### ISSUE THREAD

**Issue by Netgator** [linkedtales/scrapedin#34]
Attempted scrap of my own profile and see that both Company name and Location are not being collected due to changes in the .css of the Linkedin website.

Modifications to the "profilescrapertemplate.js" file in two places correct the issue. I have the fix in place if you would like me to submit a pull request.

otherwise the two lines should be:

     companyName: 'p.pv-entity__secondary-title',
      location: 'h4.pv-entity__location span:nth-child(2)',

**Comment by leonardiwagner** [comment]
fixed on `v1.0.9` please update your version and comment here if you still have this problem, thank you!
