### ISSUE TITLE
Error: linkedin: manual check was required, verify if your login is properly working manually or report this issue: 

### ISSUE THREAD

**Issue by tszjqgs** [linkedtales/scrapedin#37]
at page.waitFor.then.catch (/home/ubuntu/node_modules/scrapedin/src/login.js:62:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:8341) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:8341) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I verified the password manually , it was no problem , what is the reason ? thanks

**Comment by tszjqgs** [comment]
btw ,I just saw the first time manual check thing advise , but I use remote server , which are not gonna help. what platform you guys are running scrapedin on?

**Comment by leonardiwagner** [comment]
Hi @tszjqgs  we just released `v1.0.9` and now cookies option is available, now you don't have to log in on a remote server anymore, just pass the cookies and the login phase will be bypassed, please read the tutorial: https://github.com/linkedtales/scrapedin/wiki/Using-Cookies-To-Login

and please reopen and comment on this issue if you sill have this problem, thank you
