### ISSUE TITLE
linkedin is blocking the account. the program runs for a minute for a new account and then the account gets blocked....

### ISSUE THREAD

**Issue by RohitGithub87** [linkedtales/scrapedin#38]
![Screenshot 2019-10-14 21 06 37](https://user-images.githubusercontent.com/44370349/66764109-c48cae00-eec6-11e9-8b6a-49a2f275b5ed.png)

**Comment by leonardiwagner** [comment]
@RohitGithub87 have you confirmed your e-mail?

You could also try increase `waitTimeMs` parameter from `profileScraper` to throttle the crawler speed to avoid bot recognition

**Comment by RohitGithub87** [comment]
Hey Wagner,
Thanks for the very fast reply
Much appreciated.

**Comment by leonardiwagner** [comment]
@RohitGithub87 we just updated to `v1.0.9` and now login via cookies is available! I think if you use cookies you won't have this kind of problem anymore, please check: https://github.com/linkedtales/scrapedin/wiki/Using-Cookies-To-Login

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
