### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: linkedin: manual check was required..

### ISSUE THREAD

**Issue by AliOsamaHassan** [linkedtales/scrapedin#40]
UnhandledPromiseRejectionWarning: Error: linkedin: manual check was required, verify if your login is properly working manually or report this issue

**Comment by leonardiwagner** [comment]
Hi @AliOsamaHassan please check the [Tips](https://github.com/linkedtales/scrapedin/wiki/Tips) to solve manual check.

You can also consider [login via cookies](https://github.com/linkedtales/scrapedin/wiki/Using-Cookies-To-Login)

**Comment by AliOsamaHassan** [comment]
Thanks so much, It has been solved by increasing the waitTimeMs value !!! 👍 👍
