### ISSUE TITLE
More than just profile information

### ISSUE THREAD

**Issue by aner87** [linkedtales/scrapedin#42]
Hello there 👋 
The library works like a charm to retrieve information about the profile general info, thanks!!
I was wondering if I could also use it to get the latest posts of a person that I follow or that has a public profile. 
Or maybe, if it's easier, the posts related to a certain hashtag, pointing this kind of URL: https://www.linkedin.com/feed/hashtag/crypto/

Thank you 😊

**Comment by leonardiwagner** [comment]
Sure, it's related to #25 , you can create a template [like this](https://github.com/linkedtales/scrapedin/blob/master/src/profileScraperTemplate.js) and I can do the rest of the work :smile: , thank you for collaborating.

**Comment by aner87** [comment]
Thanks man, I'm gonna look into it in my free time :)
I'll let you know

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
