### ISSUE TITLE
 Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues

### ISSUE THREAD

**Issue by swozanthroop** [linkedtales/scrapedin#43]
Just running this for the first time and received that error message with the second profile I scraped. Removed the actual profile for obvious reasons.

 Here's the total error message:

(node:1944) UnhandledPromiseRejectionWarning: ReferenceError: relatedProfiles is not defined
    at crawl (C:\Program Files\nodejs\scrapedin-linkedin-crawler-master\src\crawler.js:31:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
scrapedin: 2019-10-23T18:01:11.285Z info: [profile] finished scraping url: https://www.linkedin.com/in/xxxxxxxxxxxxxxxxxx
scrapedin: 2019-10-23T18:01:11.287Z error: [cleanMessageData] LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
2019-10-23T18:01:11.290Z error: error on crawling profile: https://www.linkedin.com/in/xxxxxxxxxxxxxxx
 Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
(node:1944) UnhandledPromiseRejectionWarning: ReferenceError: relatedProfiles is not defined
    at crawl (C:\Program Files\nodejs\scrapedin-linkedin-crawler-master\src\crawler.js:31:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by syshex** [comment]
I have the same problem

**Comment by leonardiwagner** [comment]
@swozanthroop and @syshex this error is from another project: [scrapedin-linkedin-crawler](https://github.com/linkedtales/scrapedin-linkedin-crawler) please update your [crawler.js code](https://github.com/linkedtales/scrapedin-linkedin-crawler/blob/master/src/crawler.js)

**Comment by awais786327** [comment]
@leonardiwagner i am still confuse for this point 

> this error is from another project: scrapedin-linkedin-crawler please update your crawler.js code

can you explain what is **scrapedin** and what is **scrapedin-linkedin-crawler**, what are the difference ? both are different repos ?
