### ISSUE TITLE
More detailled accomplishments

### ISSUE THREAD

**Issue by Data-junkie-econs** [linkedtales/scrapedin#44]
Hello there 👋
The library works pretty well to retrieve information about the profile general info, thanks!!
I was wondering if I could also use it to get more detailed picture of accomplishments, i.e Publications, Patents, Language, etc... 
Or maybe, if it's easier to visualize the suggestion you can have a look at this profile which contained many Publications https://www.linkedin.com/in/elinlehrmann/. In that case it's will be useful for some applications to have the 75 publications descriptions.

Thank you 😊

**Comment by leonardiwagner** [comment]
@Data-junkie-econs yes, just add that info at the template: https://github.com/linkedtales/scrapedin/blob/master/src/profileScraperTemplate.js

I'll be glad having more contributors for new features, thank you

**Comment by Data-junkie-econs** [comment]
Dear @leonardiwagner thanks for your reply,
I have just tried to build the missing blocks to refine the information about achievements. However two points are to be raised, the first is my limited knowledge so I do not guarantee that this is the right solution, and the second is related to the seemore button that when it deploys one section folds up the others... 
 Publications: {
    selector: '.pv-accomplishments-block__title Publications',
    fields: {
      title: '.pv-accomplishment-entity__title',
      date: '.pv-accomplishment-entity__date',
	  Publisher: '.pv-accomplishment-entity__publisher',
	  Description: '.pv-accomplishment-entity__description t-14'
    }
  }
  

 Patents: {
    selector: '.pv-accomplishments-block__title Patents',
    fields: {
      title: '.pv-accomplishment-entity__title',
      date: '.pv-accomplishment-entity__date',
	  Number: '.pv-accomplishment-entity__issuer',
	  Description: '.pv-accomplishment-entity__description t-14'
    }
  }
  




 Languages: {
    selector: '.pv-accomplishments-block__title Languages',
    fields: {
      title: '.pv-accomplishment-entity__title',
      Proficiency: 'pv-accomplishment-entity__proficiency pv-accomplishment-entity__subtitle'
    }
  }
  

Organization: {
    selector: '.pv-accomplishments-block__title Organization',
    fields: {
      Name: 'pv-accomplishment-entity__title',
	  Position: '.pv-accomplishment-entity__position',
      date: '.pv-accomplishment-entity__date',
	  Description: '.pv-accomplishment-entity__description t-14'
    }
  }
  
  Project: {
    selector: '.pv-accomplishments-block__title Project',
    fields: {
      Name: 'pv-accomplishment-entity__title',
	  Date: '.pv-accomplishment-entity__date pv-accomplishment-entity__subtitle',
	  Description: '.pv-accomplishment-entity__description t-14'
    }
  }
 
 Courses: {
    selector: '.pv-accomplishments-block__title Courses',
    fields: {
      title: '.pv-accomplishment-entity__title',
      References: '.pv-accomplishment-entity__course-number pv-accomplishment-entity__subtitle'
    }
  } 
  
  
   Honors_Awards: {
    selector: '.pv-accomplishments-block__title Honors & Awards',
    fields: {
      title: '.pv-accomplishment-entity__title',
      date: '.pv-accomplishment-entity__date',
	  organization: '.pv-accomplishment-entity__issuer',
	  Description: '.pv-accomplishment-entity__description t-14'
    }
  }
  
   Test_Score: {
    selector: '.pv-accomplishments-block__title Test Score',
    fields: {
      title: '.pv-accomplishment-entity__title',
      Date: '.pv-accomplishment-entity__date',
	  Score: '.pv-accomplishment-entity__score'
    }
  } 


Many Thanks for your work

**Comment by Data-junkie-econs** [comment]
@leonardiwagner  I have made the template but some error appears line 175 of the following template maybe you could have a look or @Netgator  @aner87 
const alternativeProfileSelector = '.core-rail > *:first-child section >'

module.exports = {
  profileLegacy: {
    selector: '.pv-content .pv-top-card-section',
    fields: {
      name: `.pv-top-card-section__name`,
      headline: `.pv-top-card-section__headline`,
      location: `.pv-top-card-section__location`,
      connections: `.pv-top-card-v2-section__connections`
    }
  },
  profileAlternative: {
    selector: '.pv-content',
    fields: {
      name: `${alternativeProfileSelector} div:last-child > div:last-child > div:first-child ul:first-child > li:first-child`,
      headline: `${alternativeProfileSelector} div:last-child h2`,
      imageurl: {
		  selector: `${alternativeProfileSelector} div:last-child > div:first-child > div:first-child [src^="https"]`,
		  attribute: 'src'
	  },
	  location: `${alternativeProfileSelector} div:last-child > div:last-child > div:first-child ul:last-child > li:first-child`,
      connections: `${alternativeProfileSelector} div:last-child > div:last-child > div:first-child ul:last-child > li:nth-child(2)`
    }
  },
  aboutLegacy: {
    selector: '.pv-top-card-section__summary',
    fields: {
      text: '.pv-top-card-section__summary-text'
    }
  },
  aboutAlternative: {
    selector: '.pv-about-section',
    fields: {
      text: 'p'
    }
  },
  positions: {
    selector: 'section[id=experience-section] li',
    fields: {
      title: 'h3',
      companyName: '.pv-entity__secondary-title',
      location: '.pv-entity__location span:nth-child(2)',
      description: 'p[class~=pv-entity__description]',
      date1: '.pv-entity__date-range span:nth-child(2)',
      date2: '.pv-entity__bullet-item-v2',
      roles: {
        selector: '.pv-entity__role-details',
        hasChildrenFields: true,
        fields: {
          title: 'h3 span:not(.visually-hidden)',
          date1: '.pv-entity__date-range span:nth-child(2)',
          date2: '.pv-entity__bullet-item-v2',
          location: '.pv-entity__location span:nth-child(2)'
        }
      }
    }
  },
  educations: {
    selector: 'section[id=education-section] li',
    fields: {
      title: 'h3',
      degree: 'span[class=pv-entity__comma-item]',
	  fieldofstudy: 'p.pv-entity__fos span:nth-child(2)',
      date1: '.pv-entity__dates time:nth-child(1)',
      date2: '.pv-entity__dates time:nth-child(2)'
    }
  },
  skills: {
    selector: '.pv-skill-category-entity__skill-wrapper',
    fields: {
      title: '.pv-skill-category-entity__name-text',
      count: '.pv-skill-category-entity__endorsement-count'
    }
  },
  recommendationsCount: {
    selector: '.recommendations-inlining',
    fields: {
      received: 'artdeco-tab:nth-child(1)',
      given: 'artdeco-tab:nth-child(2)'
    }
  },
  recommendationsReceived: {
    selector: 'artdeco-tabpanel[aria-hidden=false] li.pv-recommendation-entity',
    fields: {
      user: {
        selector: '.pv-recommendation-entity__member',
        attribute: 'href'
      },
      text: 'blockquote.pv-recommendation-entity__text'
    }
  },
  recommendationsGiven: {
    selector: 'artdeco-tabpanel[aria-hidden=true] li.pv-recommendation-entity',
    fields: {
      user: {
        selector: '.pv-recommendation-entity__member',
        attribute: 'href'
      },
      text: 'blockquote.pv-recommendation-entity__text'
    }
  },
  accomplishments: {
    selector: 'section.pv-accomplishments-section div.ember-view',
    fields: {
     Publications: {
     selector: '.pv-accomplishments-block__title Publications',
     fields: {
      title: '.pv-accomplishment-entity__title',
      date: '.pv-accomplishment-entity__date',
	  Publisher: '.pv-accomplishment-entity__publisher',
	  Description: '.pv-accomplishment-entity__description t-14'
     }
    },
    Patents: {
    selector: '.pv-accomplishments-block__title Patents',
    fields: {
      title: '.pv-accomplishment-entity__title',
      date: '.pv-accomplishment-entity__date',
	  Number: '.pv-accomplishment-entity__issuer',
	  Description: '.pv-accomplishment-entity__description t-14'
      }
     },
    Languages: {
    selector: '.pv-accomplishments-block__title Languages',
    fields: {
      title: '.pv-accomplishment-entity__title',
      Proficiency: 'pv-accomplishment-entity__proficiency pv-accomplishment-entity__subtitle'
      }
    },
    Organization: {
    selector: '.pv-accomplishments-block__title Organization',
    fields: {
      Name: 'pv-accomplishment-entity__title',
	  Position: '.pv-accomplishment-entity__position',
      date: '.pv-accomplishment-entity__date',
	  Description: '.pv-accomplishment-entity__description t-14'
      }
    },
    Project: {
    selector: '.pv-accomplishments-block__title Project',
    fields: {
      Name: 'pv-accomplishment-entity__title',
	  Date: '.pv-accomplishment-entity__date pv-accomplishment-entity__subtitle',
	  Description: '.pv-accomplishment-entity__description t-14'
      }
    },
    Courses: {
    selector: '.pv-accomplishments-block__title Courses',
    fields: {
      title: '.pv-accomplishment-entity__title',
      References: '.pv-accomplishment-entity__course-number pv-accomplishment-entity__subtitle'
     }
    },
    Honors_Awards: {
    selector: '.pv-accomplishments-block__title Honors & Awards',
    fields: {
      title: '.pv-accomplishment-entity__title',
      date: '.pv-accomplishment-entity__date',
	  organization: '.pv-accomplishment-entity__issuer',
	  Description: '.pv-accomplishment-entity__description t-14'
      }
     },
    Test_Score: {
    selector: '.pv-accomplishments-block__title Test Score',
    fields: {
      title: '.pv-accomplishment-entity__title',
      Date: '.pv-accomplishment-entity__date',
	  Score: '.pv-accomplishment-entity__score'
      }
    } 
        }
      }
    },
    peopleAlsoViewed: {
    selector: 'li.pv-browsemap-section__member-container',
    fields: {
      user: {
        selector: 'a',
        attribute: 'href'
      },
      text: 'p'
     } 
    },
  volunteerExperience: {
    selector: 'section.volunteering-section li',
    fields: {
      title: 'h3',
      experience: 'span[class=pv-entity__secondary-title]',
      location: '.pv-entity__location span:nth-child(2)',
      description: '.pv-volunteer-causes',
      date1: '.pv-entity__date-range span:nth-child(2)',
      date2: '.pv-entity__bullet-item'
    }
  }
}

 Many thanks

**Comment by Data-junkie-econs** [comment]
Maybe you could have a look at that @Yosefc ?

**Comment by Data-junkie-econs** [comment]
Dear @leonardiwagner  I had passed a couple of hours this week on the template without results...
A see-more button should be add i think in order to expand items into the accomplishments sub sections:
{
	id: 'SEE_MORE_ACCOMPLISHMENTS',
	selector: 'button.pv-accomplishments-block__expand',
	count: ????
  }

If think my template doesn't work because I'm doing wrong with the selector, the json output contains empty fields... Maybe you could send a good reference to make this template functional and allow me to contribute to this beautiful project.

Thanks man

**Comment by Data-junkie-econs** [comment]
@leonardiwagner  @Netgator @Yosefc @aner87, I put the template I have made joined to this message if one of you could have a look it's will be really nice.

Thanks man

[profileScraperTemplate.zip](https://github.com/linkedtales/scrapedin/files/3800367/profileScraperTemplate.zip)
