### ISSUE TITLE
manual check was required

### ISSUE THREAD

**Issue by rohitshukla80** [linkedtales/scrapedin#45]
Error: linkedin: manual check was required, verify if your login is properly working manually or report this issue

**Comment by gigaBITE397** [comment]
There are various Measures taken by LinkedIn to prevent manual scrapping. Check your **credentials**, check if your session has been **logged out from the LinkedIn** or check if Certain **Class is changed by LinekdIn** for certain Profile Data.

**Comment by leonardiwagner** [comment]
Hi @rohitshukla80 , please read [Tips](https://github.com/linkedtales/scrapedin/wiki/Tips) section to solve that manual check issue.
