### ISSUE TITLE
Feature Request: Contact info click and retrieve data like Email

### ISSUE THREAD

**Issue by Uter1007** [linkedtales/scrapedin#46]
Hi,

love the library so far, only missing part that I would like to have would be the option to click on the link ContactInfo and fetching the personal info like birthday + email. 

Can you give me some clues how to add this functionality or is it already been planed ? 

Cheers,
Christoph

**Comment by leonardiwagner** [comment]
@Uter1007 Hi! This feature is quite easy to do, look at [src/seeMoreButtons.js](https://github.com/linkedtales/scrapedin/blob/master/src/seeMoreButtons.js) as a reference, we do exactly that for "see more buttons", just do the same for seeing contact info

please share this feature with a PR, thank you :smile:

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
