### ISSUE TITLE
position information was not extracted 

### ISSUE THREAD

**Issue by cyanide2019** [linkedtales/scrapedin#47]
hi everyone , when I use this scraper , the past and current position information was not kept , any one know what caused this issue ? Thanks

**Comment by leonardiwagner** [comment]
Hi, @cyanide2019 we need more information such as the profile link which this problem happens.

**Comment by cyanide2019** [comment]
https://www.linkedin.com/in/lakeisha-anderson-96527a1b/

the result is this 

{ profileLegacy: undefined,
 profileAlternative:
  { name: 'LaKeisha Anderson',
    headline: 'School bus driver/ culinary arts (baking and pastry) school',
    location: 'Chicago, Illinois',
    connections: '35',
    summary: 'Experienced School Bus Driver skilled in Catering, Food & Beverage, Event Planning, Microsoft Excel, and Customer Service. Strong operations professional.' },
 aboutLegacy: undefined,
 aboutAlternative:
  { text: 'Experienced School Bus Driver skilled in Catering, Food & Beverage, Event Planning, Microsoft Excel, and Customer Service. Strong operations professional.' },
 positions: [],
 educations:
  [ { title: 'kennedy king',
      degree: 'culinary arts',
      date1: '2003',
      date2: '2006' },
    { title: 'dunbar vocational career academy',
      date1: '1993',
      date2: '1997' } ],
 skills:
  [ { title: 'Cooking', count: '2' },
    { title: 'Nutrition', count: '2' },
    { title: 'Customer Service', count: '1' },
    { title: 'Social Media' },
    { title: 'Event Planning' },
    { title: 'Sales' },
    { title: 'Event Management' },
    { title: 'Catering' },
    { title: 'Food' },
    { title: 'Microsoft Office' },
    { title: 'Microsoft Word' },
    { title: 'Microsoft Excel' },
    { title: 'Team Building' },
    { title: 'Coaching' },
    { title: 'Hospitality' },
    { title: 'Social Networking' } ],
 recommendations: { givenCount: '0', receivedCount: '0', given: [], received: [] },
 accomplishments: [],
 peopleAlsoViewed:
  [ { user: 'https://www.linkedin.com/in/davieschr/',
      text: 'Account Manager at C.H. Robinson' } ],
 volunteerExperience: [],
 profile:
  { name: 'LaKeisha Anderson',
    headline: 'School bus driver/ culinary arts (baking and pastry) school',
    location: 'Chicago, Illinois',
    connections: '35',
    summary: 'Experienced School Bus Driver skilled in Catering, Food & Beverage, Event Planning, Microsoft Excel, and Customer Service. Strong operations professional.' } }

**Comment by leonardiwagner** [comment]
Hi @cyanide2019 I just made a test and it's working for me, please open manually in your browser, then save the page as html and post here, because it could be a regional difference that I can't have in my country: 
```json
{
  "contact": {},
  "profileAlternative": {
    "name": "LaKeisha Anderson",
    "headline": "School bus driver/ culinary arts (baking and pastry) school",
    "imageurl": "https://media.licdn.com/dms/image/C4E03AQG4c5OqThiSrg/profile-displayphoto-shrink_200_200/0?e=1578528000&v=beta&t=zQlakIc86sHRSkXe6I_3CwzPPsRkFh-aVQjG48WDjqk",
    "location": "Chicago, Illinois",
    "connections": "35",
    "summary": "Experienced School Bus Driver skilled in Catering, Food & Beverage, Event Planning, Microsoft Excel, and Customer Service. Strong operations professional."
  },
  "aboutAlternative": {
    "text": "Experienced School Bus Driver skilled in Catering, Food & Beverage, Event Planning, Microsoft Excel, and Customer Service. Strong operations professional."
  },
  "positions": [
    {
      "title": "Bus Driver",
      "companyName": "Chicago Transit Authority",
      "location": "Greater Chicago Area",
      "date1": "Feb 2017 – Present",
      "date2": "2 yrs 10 mos"
    },
    {
      "title": "School Bus Driver",
      "companyName": "Illinois Central School Bus",
      "date1": "Jun 2009 – Dec 2016",
      "date2": "7 yrs 7 mos"
    },
    {
      "title": "Customer Service Representative",
      "companyName": "The Home Depot",
      "date1": "Apr 2005 – May 2007",
      "date2": "2 yrs 2 mos"
    }
  ],
  "educations": [
    {
      "title": "kennedy king",
      "degree": "culinary arts",
      "fieldofstudy": "culinary arts",
      "date1": "2003",
      "date2": "2006"
    },
    {
      "title": "dunbar vocational career academy",
      "date1": "1993",
      "date2": "1997"
    }
  ],
  "skills": [
    {
      "title": "Cooking",
      "count": "2"
    },
    {
      "title": "Nutrition",
      "count": "2"
    },
    {
      "title": "Customer Service",
      "count": "1"
    },
    {
      "title": "Social Media"
    },
    {
      "title": "Event Planning"
    },
    {
      "title": "Sales"
    },
    {
      "title": "Event Management"
    },
    {
      "title": "Catering"
    },
    {
      "title": "Food"
    },
    {
      "title": "Microsoft Office"
    },
    {
      "title": "Microsoft Word"
    },
    {
      "title": "Microsoft Excel"
    },
    {
      "title": "Team Building"
    },
    {
      "title": "Coaching"
    },
    {
      "title": "Hospitality"
    },
    {
      "title": "Social Networking"
    }
  ],
  "recommendations": {
    "givenCount": "0",
    "receivedCount": "0",
    "given": [],
    "received": []
  },
  "accomplishments": [],
  "peopleAlsoViewed": [
    {
      "user": "https://www.linkedin.com/in/davieschr/",
      "text": "Account Manager at C.H. Robinson"
    }
  ],
  "volunteerExperience": [],
  "profile": {
    "name": "LaKeisha Anderson",
    "headline": "School bus driver/ culinary arts (baking and pastry) school",
    "imageurl": "https://media.licdn.com/dms/image/C4E03AQG4c5OqThiSrg/profile-displayphoto-shrink_200_200/0?e=1578528000&v=beta&t=zQlakIc86sHRSkXe6I_3CwzPPsRkFh-aVQjG48WDjqk",
    "location": "Chicago, Illinois",
    "connections": "35",
    "summary": "Experienced School Bus Driver skilled in Catering, Food & Beverage, Event Planning, Microsoft Excel, and Customer Service. Strong operations professional."
  }
}
```

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback. Positions gathering had several improvements at `v1.011` please update your version.
