### ISSUE TITLE
Seemore Accomplishments

### ISSUE THREAD

**Issue by Data-junkie-econs** [linkedtales/scrapedin#53]
Hi @leonardiwagner, i'm still working on the accomplishments however the behaviour of the deployment of its subsections seems to be quite different from other sections. Actually that's what I'm able to obtain for the following profile linkedin.com/in/elinlehrmann: 
{"contact":[{"type":"Elin’s Profile","values":["linkedin.com/in/elinlehrmann"]},{"type":"Website","values":["orcid.org/0000-0002-9869-9475  (Portfolio)"]}],
"profileAlternative":{"name":"Elin Lehrmann, Ph.D.","headline":"Scientist | Versatilist | Mentor | Life-long learner |","imageurl":"https://media.licdn.com/dms/image/C5603AQElAkv6ZVoRUg/profile-displayphoto-shrink_200_200/0?e=1578528000&v=beta&t=IjvhkUhwXMoYY3pmmPqTKV7JJ5IwqHNOLAijZn6N-ZI","location":"Baltimore, Maryland","connections":"406","summary":"Ph.D.-level biomedical scientist skilled in designing and implementing effective cross-disciplinary collaborations with individuals and teams from diverse backgrounds and organizational levels that translate novel information into validated data and peer-reviewed knowledge using complex analytical and problem-solving abilities to optimize workflow, information quality, and project delivery."},
"aboutAlternative":{"text":"Ph.D.-level biomedical scientist skilled in designing and implementing effective cross-disciplinary collaborations with individuals and teams from diverse backgrounds and organizational levels that translate novel information into validated data and peer-reviewed knowledge using complex analytical and problem-solving abilities to optimize workflow, information quality, and project delivery."},
"positions":[{"title":"Biologist","companyName":"National Institutes of Health (NIH): Intramural Research Program (IRP)","date1":"Oct 2008 – Present","date2":"11 yrs 2 mos"},{"title":"Staff Fellow","companyName":"National Institute on Drug Abuse (NIDA IRP), NIH","date1":"2000 – 2008","date2":"8 yrs"},{"title":"Postdoctoral Research Fellow","companyName":"Maryland Psychiatric Research Center (MRPC), University of Maryland School of Medicine","date1":"1996 – 2000","date2":"4 yrs"},{"title":"Ph.D. (Neuroscience)","companyName":"University of Southern Denmark, School of Medicine","date1":"1992 – 1996","date2":"4 yrs"},{"title":"Department of Anatomy (SOM), Aarhus University","location":"Aarhus, Denmark","date1":"1990 – 1992","date2":"2 yrs","roles":[{"title":"Research Assistant","date1":"1990 – 1992","date2":"2 yrs","location":"Aarhus, Denmark"},{"title":"Cand. Scient. (M.Sc.; Biology/Chemistry)","date1":"1984 – 1992","date2":"8 yrs"}]},{"title":"Title\nResearch Assistant","location":"Aarhus, Denmark","date1":"1990 – 1992","date2":"2 yrs","roles":[{"title":"Research Assistant","date1":"1990 – 1992","date2":"2 yrs","location":"Aarhus, Denmark"}]},{"title":"Title\nCand. Scient. (M.Sc.; Biology/Chemistry)","date1":"1984 – 1992","date2":"8 yrs","roles":[{"title":"Cand. Scient. (M.Sc.; Biology/Chemistry)","date1":"1984 – 1992","date2":"8 yrs"}]}],
"educations":[{"title":"University of Southern Denmark","degree":"Ph.D.","fieldofstudy":"Neuroscience","date1":"1992","date2":"1996"},{"title":"Aarhus University","degree":"Cand. Scient.","fieldofstudy":"Biology (MSc), Chemistry (BSc)","date1":"1984","date2":"1992"}],
"skills":[{"title":"Analysis","count":"1"},{"title":"Problem Solving","count":"1"},{"title":"Project Planning","count":"1"},{"title":"Project Management"},{"title":"Foreign Languages"},{"title":"Nonprofit Organizations"},{"title":"Lifesciences","count":"3"},{"title":"Neuroscience","count":"41"},{"title":"Molecular Biology","count":"34"},{"title":"Genetics","count":"15"},{"title":"Bioinformatics","count":"6"},{"title":"Strategic Planning"},{"title":"Immunohistochemistry","count":"22"},{"title":"qPCR","count":"23"},{"title":"PCR","count":"14"},{"title":"Research","count":"6"},{"title":"Genomics","count":"6"},{"title":"Biotechnology","count":"6"},{"title":"Clinical Research","count":"3"},{"title":"Writing"},{"title":"Life Sciences","count":"19"},{"title":"Data Analysis","count":"2"},{"title":"Social Media"},{"title":"Marketing"},{"title":"Spreadsheets"},{"title":"Event Planning"},{"title":"Event Management"},{"title":"PowerPoint"},{"title":"Microsoft Word"},{"title":"Microsoft Excel"},{"title":"Microsoft Office"},{"title":"Time Management"},{"title":"Team Leadership"},{"title":"Public Speaking"},{"title":"Leadership"},{"title":"Teamwork"},{"title":"Management"},{"title":"Personal Development"},{"title":"Communication"},{"title":"Professional Ethics"},{"title":"Cross-disciplinary collaboration"},{"title":"Leading Meetings"},{"title":"In Vivo","count":"19"},{"title":"Life Skills"},{"title":"Sequencing","count":"3"},{"title":"Translational Medicine","count":"1"},{"title":"Toxicology","count":"1"},{"title":"Peer Reviews"},{"title":"Peer Mentoring"},{"title":"Computational Biology","count":"1"}],
"recommendations":{"givenCount":"0","receivedCount":"0","given":[],"received":[]},
"accomplishments":[{"Publications":["Elin has 75 publications\n75\nPublications\npublication title\nLoss of miR-451a enhances SPARC production during myogenesis.\n\npublication date\nMar 29, 2019  \npublication description\nPLoS One. 2019 Mar 29;14(3):e0214301.\n\npublication description\nAbstract. MicroRNAs (miRNAs) are small noncoding RNAs that critically regulate gene expression. Their abundance and function have been linked to a range of physiologic and pathologic processes. In aged monkey muscle, miR-451a and miR-144-3p were far more abundant than in young monkey muscle. This observation led us to hypothesize that miR-451a and miR-144-3p may influence muscle homeostasis. To test if these conserved microRNAs were implicated in myogenesis, we investigated their function in the mouse myoblast line C2C12. The levels of both microRNAs declined with myogenesis; however, only overexpression of miR-451a, but not miR-144-3p, robustly impeded C2C12 differentiation, suggesting an inhibitory role for miR-451a in myogenesis. Further investigation of the regulatory influence of miR-451a identified as one of the major targets Sparc mRNA, which encodes a secreted protein acidic and rich in cysteine (SPARC) that functions in wound healing and cellular differentiation. In mouse myoblasts, miR-451a suppressed Sparc mRNA translation. Together, our findings indicate that miR-451a is downregulated in differentiated myoblasts and suggest that it decreases C2C12 differentiation at least in part by suppressing SPARC biosynthesis.\n\nLoss of miR-451a enhances SPARC production during myogenesis. Munk R, Martindale JL, Yang X, Yang JH, Grammatikakis I, Di Germanio C, Mitchell SJ, de Cabo R, Lehrmann E, Zhang Y, Becker KG, Raz V, Gorospe M, Abdelmohsen K, Panda AC. PLoS One. 2019 Mar 29;14(3):e0214301. doi: 10.1371/journal.pone.0214301. eCollection 2019.\nPMID: 30925184\n\nSee publication Loss of miR-451a enhances SPARC production during myogenesis.\nSee publication\npublication title\nMuscle cannabinoid 1 receptor regulates Il-6 and myostatin expression, governing physical performance and whole-body metabolism.\n\npublication date\nFeb 6, 2019  \npublication description\nFASEB J. 2019 Feb 6:fj201801145R. doi: 10.1096/fj.201801145R. [Epub ahead of print]\n\npublication description\nAbstract. Sarcopenic obesity, the combination of skeletal muscle mass and function loss with an increase in body fat, is associated with physical limitations, cardiovascular diseases, metabolic stress, and increased risk of mortality. Cannabinoid receptor type 1 (CB1R) plays a critical role in the regulation of whole-body energy metabolism because of its involvement in controlling appetite, fuel distribution, and utilization. Inhibition of CB1R improves insulin secretion and insulin sensitivity in pancreatic β-cells and hepatocytes. We have now developed a skeletal muscle–specific CB1R-knockout (Skm-CB1R−/−) mouse to study the specific role of CB1R in muscle. Muscle-CB1R ablation prevented diet-induced and age-induced insulin resistance by increasing IR signaling. Moreover, muscle-CB1R ablation enhanced AKT signaling, reducing myostatin expression and increasing IL-6 secretion. Subsequently, muscle-CB1R ablation increased myogenesis through its action on MAPK-mediated myogenic gene expression. Consequently, Skm-CB1R−/− mice had increased muscle mass and whole-body lean/fat ratio in obesity and aging. Muscle-CB1R ablation improved mitochondrial performance, leading to increased whole-body muscle energy expenditure and improved physical endurance, with no change in body weight. These results collectively show that CB1R in muscle is sufficient to regulate whole-body metabolism and physical performance and is a novel target for the treatment of sarcopenic obesity.\n\nGonzález-Mariscal I, Montoro RA, O'Connell JF, Kim Y, Gonzalez-Freire M, Liu QR, Alfaras I, Carlson OD, Lehrmann E, Zhang Y, Becker KG, Hardivillé S, Ghosh P, Egan JM. Muscle cannabinoid 1 receptor regulates Il-6 and myostatin expression, governing physical performance and whole-body metabolism. FASEB J. 2019 Feb 6:fj201801145R. doi: 10.1096/fj.201801145R. [Epub ahead of print]\nPMID: 30726112\n\nSee publication Muscle cannabinoid 1 receptor regulates Il-6 and myostatin expression, governing physical performance and whole-body metabolism.\nSee publication\npublication title\nTopoisomerase 3β interacts with RNAi machinery to promote heterochromatin formation and transcriptional silencing in Drosophila.\n\npublication date\nNov 23, 2018  \npublication description\nNat Commun .9(1): 4946.\n\npublication description\nLee SK, Xue Y, Shen W, Zhang Y, Joo Y, Ahmad M, Chinen M, Ding Y, Ku WL, De S, Lehrmann E, Becker KG, Lei EP, Zhao K, Zou S, Sharov A, Wang W. Topoisomerase 3β interacts with RNAi machinery to promote heterochromatin formation and transcriptional silencing in Drosophila. Nat Commun. 2018 Nov 23;9(1):4946. doi: 10.1038/s41467-018-07101-4.\nPMID: 30470739\nDOI: 10.1038/s41467-018-07101-4\n\nAbstract. Topoisomerases solve topological problems during DNA metabolism, but whether they participate in RNA metabolism remains unclear. Top3β represents a family of topoisomerases carrying activities for both DNA and RNA. Here we show that in Drosophila, Top3β interacts biochemically and genetically with the RNAi-induced silencing complex (RISC) containing AGO2, p68 RNA helicase, and FMRP. Top3β and RISC mutants are similarly defective in heterochromatin formation and transcriptional silencing by position-effect variegation assay. Moreover, both Top3β and AGO2 mutants exhibit reduced levels of heterochromatin protein HP1 in heterochromatin. Furthermore, expression of several genes and transposable elements in heterochromatin is increased in the Top3β mutant. Notably, Top3β mutants defective in either RNA binding or catalytic activity are deficient in promoting HP1 recruitment and silencing of transposable elements. Our data suggest that Top3β may act as an RNA topoisomerase in siRNA-guided heterochromatin formation and transcriptional silencing.\n\nSee publication Topoisomerase 3β interacts with RNAi machinery to promote heterochromatin formation and transcriptional silencing in Drosophila.\nSee publication\npublication title\nHydroxyurea attenuates oxidative, metabolic, and excitotoxic stress in rat hippocampal neurons and improves spatial memory in a mouse model of Alzheimer’s disease\n\npublication date\nAug 29, 2018  \npublication description\nNeurobiology of Aging\n\npublication description\nRD Brose, E Lehrmann, Y Zhang, RH Reeves, KD Smith, MP Mattson (2018).\nHydroxyurea attenuates oxidative, metabolic, and excitotoxic stress in rat hippocampal neurons and improves spatial memory in a mouse model of Alzheimer’s disease\nNeurobiology of Aging\nhttps://doi.org/10.1016/j.neurobiolaging.2018.08.021 [Epub ahead of print]\n\nSee publication Hydroxyurea attenuates oxidative, metabolic, and excitotoxic stress in rat hippocampal neurons and improves spatial memory in a mouse model of Alzheimer’s disease\nSee publication\npublication title\nMIR100 host gene-encoded lncRNAs regulate cell cycle by modulating the interaction between HuR and its target mRNAs.\n\npublication date\nAug 8, 2018  \npublication description\nNucleic Acids Res.\n\npublication description\nSun Q, Tripathi V, Yoon JH, Singh DK, Hao Q, Min KW, Davila S, Zealy RW, Li XL, Polycarpou-Schwarz M, Lehrmann E, Zhang Y, Becker KG, Freier SM, Zhu Y, Diederichs S, Prasanth SG, Lal A, Gorospe M, Prasanth KV. MIR100 host gene-encoded lncRNAs regulate cell cycle by modulating the interaction between HuR and its target mRNAs.\nNucleic Acids Res. 2018 Aug 8. doi: 10.1093/nar/gky696. [Epub ahead of print]\nPMID: 30102375\n\nSee publication MIR100 host gene-encoded lncRNAs regulate cell cycle by modulating the interaction between HuR and its target mRNAs.\nSee publication\nShow more"]},{},{}],

"peopleAlsoViewed":[{"user":"https://www.linkedin.com/in/kate-wilson-0a42407/","text":"Senior Director of Sustainability at Vail Resorts"},{"user":"https://www.linkedin.com/in/maire-doyle-b85a262b/","text":"Scientist (C) Principal Investigator, Role of insulin in taste transduction, cultivation of taste cell precursors"},{"user":"https://www.linkedin.com/in/marcellebergeron/","text":"Drug Development Professional"},{"user":"https://www.linkedin.com/in/saeed-azimi-a5bb1544/","text":"Immunotherapy"},{"user":"https://www.linkedin.com/in/hyun-k-1435627/","text":"Drug development"},{"user":"https://www.linkedin.com/in/jared-kartchner-b5229770/","text":"Attorney at Northern Virginia Estate Planning Services"},{"user":"https://www.linkedin.com/in/emily-hm-wong-919b7975/","text":"Scientist II, Computational Biology"},{"user":"https://www.linkedin.com/in/tomrohmann/","text":"Service Order Program Manager at J&J Worldwide Services"},{"user":"https://www.linkedin.com/in/lukecartin/","text":"Environmental Sustainability Manager at Park City Municipal Corporation"},{"user":"https://www.linkedin.com/in/martina-molsbergen-ba9b438/","text":"CEO at C14 Consulting Group, LLC"}],
"volunteerExperience":[{"title":"Organizing Committee member","experience":"Rhodesian Ridgeback World Congress 2016","description":"Animal Welfare","date1":"Sep 2014 – Aug 2016","date2":"2 yrs"},{"title":"Vice-President","experience":"Chesapeake Bay Area Rhodesian Ridgeback Club","description":"Animal Welfare","date1":"Jul 2015 – Present","date2":"4 yrs 5 mos"},{"title":"Treasurer","experience":"Chesapeake Bay Area Rhodesian Ridgeback Club","description":"Animal Welfare","date1":"Aug 2013 – Nov 2014","date2":"1 yr 4 mos"},{"title":"Member","experience":"Rhodesian Ridgeback World Congress Health Committee","description":"Animal Welfare","date1":"Jul 2016 – Present","date2":"3 yrs 5 mos"},{"title":"Regional News Column","experience":"Chesapeake Bay Area Rhodesian Ridgeback Club","description":"Animal Welfare","date1":"Aug 2017 – Present","date2":"2 yrs 4 mos"}],"profile":{"name":"Elin Lehrmann, Ph.D.","headline":"Scientist | Versatilist | Mentor | Life-long learner |","imageurl":"https://media.licdn.com/dms/image/C5603AQElAkv6ZVoRUg/profile-displayphoto-shrink_200_200/0?e=1578528000&v=beta&t=IjvhkUhwXMoYY3pmmPqTKV7JJ5IwqHNOLAijZn6N-ZI","location":"Baltimore, Maryland","connections":"406","summary":"Ph.D.-level biomedical scientist skilled in designing and implementing effective cross-disciplinary collaborations with individuals and teams from diverse backgrounds and organizational levels that translate novel information into validated data and peer-reviewed knowledge using complex analytical and problem-solving abilities to optimize workflow, information quality, and project delivery."}}

As you can see, I only scrap 5 of the 75 publications display on that profile, I cannot obtain the link to the publications, and the languages part is not scraped.... I think this issue is related to two others issue, the number #1 and the number #36 . I have try to make some modifications to the seemore functions without any results.... I join the modified seemore file, I think making the code a bit more sequential could help us to tackle that issue but I don't know how to do that.
[seemore.txt](https://github.com/linkedtales/scrapedin/files/3825375/seemore.txt)

Thanks man!

**Comment by Data-junkie-econs** [comment]
Hi @leonardiwagner, i'm still working on the accomplishments however the behaviour of the deployment of its subsections seems to be quite different from other sections. At that time I cannot deploy that using the button selector.... Could you look at this point?
Thanks man

**Comment by Data-junkie-econs** [comment]
Actually that's what I'm able to obtain for the following profil linkedin.com/in/elinlehrmann: 
{"contact":[{"type":"Elin’s Profile","values":["linkedin.com/in/elinlehrmann"]},{"type":"Website","values":["orcid.org/0000-0002-9869-9475  (Portfolio)"]}],
"profileAlternative":{"name":"Elin Lehrmann, Ph.D.","headline":"Scientist | Versatilist | Mentor | Life-long learner |","imageurl":"https://media.licdn.com/dms/image/C5603AQElAkv6ZVoRUg/profile-displayphoto-shrink_200_200/0?e=1578528000&v=beta&t=IjvhkUhwXMoYY3pmmPqTKV7JJ5IwqHNOLAijZn6N-ZI","location":"Baltimore, Maryland","connections":"406","summary":"Ph.D.-level biomedical scientist skilled in designing and implementing effective cross-disciplinary collaborations with individuals and teams from diverse backgrounds and organizational levels that translate novel information into validated data and peer-reviewed knowledge using complex analytical and problem-solving abilities to optimize workflow, information quality, and project delivery."},
"aboutAlternative":{"text":"Ph.D.-level biomedical scientist skilled in designing and implementing effective cross-disciplinary collaborations with individuals and teams from diverse backgrounds and organizational levels that translate novel information into validated data and peer-reviewed knowledge using complex analytical and problem-solving abilities to optimize workflow, information quality, and project delivery."},
"positions":[{"title":"Biologist","companyName":"National Institutes of Health (NIH): Intramural Research Program (IRP)","date1":"Oct 2008 – Present","date2":"11 yrs 2 mos"},{"title":"Staff Fellow","companyName":"National Institute on Drug Abuse (NIDA IRP), NIH","date1":"2000 – 2008","date2":"8 yrs"},{"title":"Postdoctoral Research Fellow","companyName":"Maryland Psychiatric Research Center (MRPC), University of Maryland School of Medicine","date1":"1996 – 2000","date2":"4 yrs"},{"title":"Ph.D. (Neuroscience)","companyName":"University of Southern Denmark, School of Medicine","date1":"1992 – 1996","date2":"4 yrs"},{"title":"Department of Anatomy (SOM), Aarhus University","location":"Aarhus, Denmark","date1":"1990 – 1992","date2":"2 yrs","roles":[{"title":"Research Assistant","date1":"1990 – 1992","date2":"2 yrs","location":"Aarhus, Denmark"},{"title":"Cand. Scient. (M.Sc.; Biology/Chemistry)","date1":"1984 – 1992","date2":"8 yrs"}]},{"title":"Title\nResearch Assistant","location":"Aarhus, Denmark","date1":"1990 – 1992","date2":"2 yrs","roles":[{"title":"Research Assistant","date1":"1990 – 1992","date2":"2 yrs","location":"Aarhus, Denmark"}]},{"title":"Title\nCand. Scient. (M.Sc.; Biology/Chemistry)","date1":"1984 – 1992","date2":"8 yrs","roles":[{"title":"Cand. Scient. (M.Sc.; Biology/Chemistry)","date1":"1984 – 1992","date2":"8 yrs"}]}],
"educations":[{"title":"University of Southern Denmark","degree":"Ph.D.","fieldofstudy":"Neuroscience","date1":"1992","date2":"1996"},{"title":"Aarhus University","degree":"Cand. Scient.","fieldofstudy":"Biology (MSc), Chemistry (BSc)","date1":"1984","date2":"1992"}],
"skills":[{"title":"Analysis","count":"1"},{"title":"Problem Solving","count":"1"},{"title":"Project Planning","count":"1"},{"title":"Project Management"},{"title":"Foreign Languages"},{"title":"Nonprofit Organizations"},{"title":"Lifesciences","count":"3"},{"title":"Neuroscience","count":"41"},{"title":"Molecular Biology","count":"34"},{"title":"Genetics","count":"15"},{"title":"Bioinformatics","count":"6"},{"title":"Strategic Planning"},{"title":"Immunohistochemistry","count":"22"},{"title":"qPCR","count":"23"},{"title":"PCR","count":"14"},{"title":"Research","count":"6"},{"title":"Genomics","count":"6"},{"title":"Biotechnology","count":"6"},{"title":"Clinical Research","count":"3"},{"title":"Writing"},{"title":"Life Sciences","count":"19"},{"title":"Data Analysis","count":"2"},{"title":"Social Media"},{"title":"Marketing"},{"title":"Spreadsheets"},{"title":"Event Planning"},{"title":"Event Management"},{"title":"PowerPoint"},{"title":"Microsoft Word"},{"title":"Microsoft Excel"},{"title":"Microsoft Office"},{"title":"Time Management"},{"title":"Team Leadership"},{"title":"Public Speaking"},{"title":"Leadership"},{"title":"Teamwork"},{"title":"Management"},{"title":"Personal Development"},{"title":"Communication"},{"title":"Professional Ethics"},{"title":"Cross-disciplinary collaboration"},{"title":"Leading Meetings"},{"title":"In Vivo","count":"19"},{"title":"Life Skills"},{"title":"Sequencing","count":"3"},{"title":"Translational Medicine","count":"1"},{"title":"Toxicology","count":"1"},{"title":"Peer Reviews"},{"title":"Peer Mentoring"},{"title":"Computational Biology","count":"1"}],
"recommendations":{"givenCount":"0","receivedCount":"0","given":[],"received":[]},
"accomplishments":[{"Publications":["Elin has 75 publications\n75\nPublications\npublication title\nLoss of miR-451a enhances SPARC production during myogenesis.\n\npublication date\nMar 29, 2019  \npublication description\nPLoS One. 2019 Mar 29;14(3):e0214301.\n\npublication description\nAbstract. MicroRNAs (miRNAs) are small noncoding RNAs that critically regulate gene expression. Their abundance and function have been linked to a range of physiologic and pathologic processes. In aged monkey muscle, miR-451a and miR-144-3p were far more abundant than in young monkey muscle. This observation led us to hypothesize that miR-451a and miR-144-3p may influence muscle homeostasis. To test if these conserved microRNAs were implicated in myogenesis, we investigated their function in the mouse myoblast line C2C12. The levels of both microRNAs declined with myogenesis; however, only overexpression of miR-451a, but not miR-144-3p, robustly impeded C2C12 differentiation, suggesting an inhibitory role for miR-451a in myogenesis. Further investigation of the regulatory influence of miR-451a identified as one of the major targets Sparc mRNA, which encodes a secreted protein acidic and rich in cysteine (SPARC) that functions in wound healing and cellular differentiation. In mouse myoblasts, miR-451a suppressed Sparc mRNA translation. Together, our findings indicate that miR-451a is downregulated in differentiated myoblasts and suggest that it decreases C2C12 differentiation at least in part by suppressing SPARC biosynthesis.\n\nLoss of miR-451a enhances SPARC production during myogenesis. Munk R, Martindale JL, Yang X, Yang JH, Grammatikakis I, Di Germanio C, Mitchell SJ, de Cabo R, Lehrmann E, Zhang Y, Becker KG, Raz V, Gorospe M, Abdelmohsen K, Panda AC. PLoS One. 2019 Mar 29;14(3):e0214301. doi: 10.1371/journal.pone.0214301. eCollection 2019.\nPMID: 30925184\n\nSee publication Loss of miR-451a enhances SPARC production during myogenesis.\nSee publication\npublication title\nMuscle cannabinoid 1 receptor regulates Il-6 and myostatin expression, governing physical performance and whole-body metabolism.\n\npublication date\nFeb 6, 2019  \npublication description\nFASEB J. 2019 Feb 6:fj201801145R. doi: 10.1096/fj.201801145R. [Epub ahead of print]\n\npublication description\nAbstract. Sarcopenic obesity, the combination of skeletal muscle mass and function loss with an increase in body fat, is associated with physical limitations, cardiovascular diseases, metabolic stress, and increased risk of mortality. Cannabinoid receptor type 1 (CB1R) plays a critical role in the regulation of whole-body energy metabolism because of its involvement in controlling appetite, fuel distribution, and utilization. Inhibition of CB1R improves insulin secretion and insulin sensitivity in pancreatic β-cells and hepatocytes. We have now developed a skeletal muscle–specific CB1R-knockout (Skm-CB1R−/−) mouse to study the specific role of CB1R in muscle. Muscle-CB1R ablation prevented diet-induced and age-induced insulin resistance by increasing IR signaling. Moreover, muscle-CB1R ablation enhanced AKT signaling, reducing myostatin expression and increasing IL-6 secretion. Subsequently, muscle-CB1R ablation increased myogenesis through its action on MAPK-mediated myogenic gene expression. Consequently, Skm-CB1R−/− mice had increased muscle mass and whole-body lean/fat ratio in obesity and aging. Muscle-CB1R ablation improved mitochondrial performance, leading to increased whole-body muscle energy expenditure and improved physical endurance, with no change in body weight. These results collectively show that CB1R in muscle is sufficient to regulate whole-body metabolism and physical performance and is a novel target for the treatment of sarcopenic obesity.\n\nGonzález-Mariscal I, Montoro RA, O'Connell JF, Kim Y, Gonzalez-Freire M, Liu QR, Alfaras I, Carlson OD, Lehrmann E, Zhang Y, Becker KG, Hardivillé S, Ghosh P, Egan JM. Muscle cannabinoid 1 receptor regulates Il-6 and myostatin expression, governing physical performance and whole-body metabolism. FASEB J. 2019 Feb 6:fj201801145R. doi: 10.1096/fj.201801145R. [Epub ahead of print]\nPMID: 30726112\n\nSee publication Muscle cannabinoid 1 receptor regulates Il-6 and myostatin expression, governing physical performance and whole-body metabolism.\nSee publication\npublication title\nTopoisomerase 3β interacts with RNAi machinery to promote heterochromatin formation and transcriptional silencing in Drosophila.\n\npublication date\nNov 23, 2018  \npublication description\nNat Commun .9(1): 4946.\n\npublication description\nLee SK, Xue Y, Shen W, Zhang Y, Joo Y, Ahmad M, Chinen M, Ding Y, Ku WL, De S, Lehrmann E, Becker KG, Lei EP, Zhao K, Zou S, Sharov A, Wang W. Topoisomerase 3β interacts with RNAi machinery to promote heterochromatin formation and transcriptional silencing in Drosophila. Nat Commun. 2018 Nov 23;9(1):4946. doi: 10.1038/s41467-018-07101-4.\nPMID: 30470739\nDOI: 10.1038/s41467-018-07101-4\n\nAbstract. Topoisomerases solve topological problems during DNA metabolism, but whether they participate in RNA metabolism remains unclear. Top3β represents a family of topoisomerases carrying activities for both DNA and RNA. Here we show that in Drosophila, Top3β interacts biochemically and genetically with the RNAi-induced silencing complex (RISC) containing AGO2, p68 RNA helicase, and FMRP. Top3β and RISC mutants are similarly defective in heterochromatin formation and transcriptional silencing by position-effect variegation assay. Moreover, both Top3β and AGO2 mutants exhibit reduced levels of heterochromatin protein HP1 in heterochromatin. Furthermore, expression of several genes and transposable elements in heterochromatin is increased in the Top3β mutant. Notably, Top3β mutants defective in either RNA binding or catalytic activity are deficient in promoting HP1 recruitment and silencing of transposable elements. Our data suggest that Top3β may act as an RNA topoisomerase in siRNA-guided heterochromatin formation and transcriptional silencing.\n\nSee publication Topoisomerase 3β interacts with RNAi machinery to promote heterochromatin formation and transcriptional silencing in Drosophila.\nSee publication\npublication title\nHydroxyurea attenuates oxidative, metabolic, and excitotoxic stress in rat hippocampal neurons and improves spatial memory in a mouse model of Alzheimer’s disease\n\npublication date\nAug 29, 2018  \npublication description\nNeurobiology of Aging\n\npublication description\nRD Brose, E Lehrmann, Y Zhang, RH Reeves, KD Smith, MP Mattson (2018).\nHydroxyurea attenuates oxidative, metabolic, and excitotoxic stress in rat hippocampal neurons and improves spatial memory in a mouse model of Alzheimer’s disease\nNeurobiology of Aging\nhttps://doi.org/10.1016/j.neurobiolaging.2018.08.021 [Epub ahead of print]\n\nSee publication Hydroxyurea attenuates oxidative, metabolic, and excitotoxic stress in rat hippocampal neurons and improves spatial memory in a mouse model of Alzheimer’s disease\nSee publication\npublication title\nMIR100 host gene-encoded lncRNAs regulate cell cycle by modulating the interaction between HuR and its target mRNAs.\n\npublication date\nAug 8, 2018  \npublication description\nNucleic Acids Res.\n\npublication description\nSun Q, Tripathi V, Yoon JH, Singh DK, Hao Q, Min KW, Davila S, Zealy RW, Li XL, Polycarpou-Schwarz M, Lehrmann E, Zhang Y, Becker KG, Freier SM, Zhu Y, Diederichs S, Prasanth SG, Lal A, Gorospe M, Prasanth KV. MIR100 host gene-encoded lncRNAs regulate cell cycle by modulating the interaction between HuR and its target mRNAs.\nNucleic Acids Res. 2018 Aug 8. doi: 10.1093/nar/gky696. [Epub ahead of print]\nPMID: 30102375\n\nSee publication MIR100 host gene-encoded lncRNAs regulate cell cycle by modulating the interaction between HuR and its target mRNAs.\nSee publication\nShow more"]},{},{}],

"peopleAlsoViewed":[{"user":"https://www.linkedin.com/in/kate-wilson-0a42407/","text":"Senior Director of Sustainability at Vail Resorts"},{"user":"https://www.linkedin.com/in/maire-doyle-b85a262b/","text":"Scientist (C) Principal Investigator, Role of insulin in taste transduction, cultivation of taste cell precursors"},{"user":"https://www.linkedin.com/in/marcellebergeron/","text":"Drug Development Professional"},{"user":"https://www.linkedin.com/in/saeed-azimi-a5bb1544/","text":"Immunotherapy"},{"user":"https://www.linkedin.com/in/hyun-k-1435627/","text":"Drug development"},{"user":"https://www.linkedin.com/in/jared-kartchner-b5229770/","text":"Attorney at Northern Virginia Estate Planning Services"},{"user":"https://www.linkedin.com/in/emily-hm-wong-919b7975/","text":"Scientist II, Computational Biology"},{"user":"https://www.linkedin.com/in/tomrohmann/","text":"Service Order Program Manager at J&J Worldwide Services"},{"user":"https://www.linkedin.com/in/lukecartin/","text":"Environmental Sustainability Manager at Park City Municipal Corporation"},{"user":"https://www.linkedin.com/in/martina-molsbergen-ba9b438/","text":"CEO at C14 Consulting Group, LLC"}],
"volunteerExperience":[{"title":"Organizing Committee member","experience":"Rhodesian Ridgeback World Congress 2016","description":"Animal Welfare","date1":"Sep 2014 – Aug 2016","date2":"2 yrs"},{"title":"Vice-President","experience":"Chesapeake Bay Area Rhodesian Ridgeback Club","description":"Animal Welfare","date1":"Jul 2015 – Present","date2":"4 yrs 5 mos"},{"title":"Treasurer","experience":"Chesapeake Bay Area Rhodesian Ridgeback Club","description":"Animal Welfare","date1":"Aug 2013 – Nov 2014","date2":"1 yr 4 mos"},{"title":"Member","experience":"Rhodesian Ridgeback World Congress Health Committee","description":"Animal Welfare","date1":"Jul 2016 – Present","date2":"3 yrs 5 mos"},{"title":"Regional News Column","experience":"Chesapeake Bay Area Rhodesian Ridgeback Club","description":"Animal Welfare","date1":"Aug 2017 – Present","date2":"2 yrs 4 mos"}],"profile":{"name":"Elin Lehrmann, Ph.D.","headline":"Scientist | Versatilist | Mentor | Life-long learner |","imageurl":"https://media.licdn.com/dms/image/C5603AQElAkv6ZVoRUg/profile-displayphoto-shrink_200_200/0?e=1578528000&v=beta&t=IjvhkUhwXMoYY3pmmPqTKV7JJ5IwqHNOLAijZn6N-ZI","location":"Baltimore, Maryland","connections":"406","summary":"Ph.D.-level biomedical scientist skilled in designing and implementing effective cross-disciplinary collaborations with individuals and teams from diverse backgrounds and organizational levels that translate novel information into validated data and peer-reviewed knowledge using complex analytical and problem-solving abilities to optimize workflow, information quality, and project delivery."}}

As you can see, I only scrap 5 of the 75 publications display on that profil, I cannot obtain the link to the publications, and the languages part is not scraped.... I think this issue is related to two others issue, the number #1 and the number #36 . I have try to make some modifications to the seemore functions without any results.... 

Thanks man

**Comment by EmaSuriano** [comment]
Hello, I implemented the feature to return Projects, Languages, and Courses in this PR. I think it's quite related with this issue! #89

**Comment by leonardiwagner** [comment]
added on v`1.0.15` , thank you all!
