### ISSUE TITLE
Issue in live server

### ISSUE THREAD

**Issue by rohitshukla80** [linkedtales/scrapedin#55]
Hi Team,

This is working fine in local server. but same code is not working in live server. So pls check and help me for solve this problem.

Error: Protocol error (Runtime.callFunctionOn): Target closed.

**Comment by leonardiwagner** [comment]
- Who displays that error? and where?
- Use `hasToLog` [option](https://github.com/linkedtales/scrapedin/wiki/Documentation#--options-object) to provide more description and post logs here
- [using cookies](https://github.com/linkedtales/scrapedin/wiki/Using-Cookies-To-Login) is the recommended way to run on remote servers

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback.
