### ISSUE TITLE
how to get "Contact Info"

### ISSUE THREAD

**Issue by havid0707** [linkedtales/scrapedin#60]
it is that possible to scrape the "Contact Info" in every profile? Thanks a lot

**Comment by leonardiwagner** [comment]
Hi @havid0707 why did you close the issue? :smile: 

I just released the `v1.0.11` version, now it's possible to collect "contact info"

See get contact section [on documentation](https://github.com/linkedtales/scrapedin/wiki/Documentation#--options-object) and update your scrapedin version.

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
