### ISSUE TITLE
No profile to crawl right now

### ISSUE THREAD

**Issue by awais786327** [linkedtales/scrapedin#61]
@leonardiwagner thanks for this great stuff i am using your library to crawl but it says no profile to crawl right now can you please fix this

![image](https://user-images.githubusercontent.com/12613564/70309051-6dec8200-182e-11ea-866f-656442e05d3e.png)

**Comment by awais786327** [comment]
this is my config.json

{
  "email": "myemail@gmail.com",
  "password": "mypass",
  "cookiesFile": "./linkedincookie.txt",
  "relatedProfilesKeywords": [],
  "maxConcurrentCrawlers": 2,
  "profileLoadWaitTime": 5000,
  "saveDirectory": "./crawledProfiles",
  "puppeteerArgs": { "args": ["--no-sandbox"] },
  "isHeadless": true,
  "hasToLog": true,
  "proxyAddress": null,
  "rootProfiles": [
    "https://www.linkedin.com/in/syed-asher-ahmed-6762b6134/",
    "https://www.linkedin.com/in/syed-asher-ahmed-6762b6134/detail/contact-info/"
  ]
}

**Comment by leonardiwagner** [comment]
answered there: https://github.com/linkedtales/scrapedin-linkedin-crawler/issues/31
