### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by havid0707** [linkedtales/scrapedin#62]
when I use "args":["--no-sandbox","--proxy-server=http://server:port"]}, can not login linkedin.
always prompt "manual check was required".

just want to know, is there anybody scrape profile with proxy successfuly?

**Comment by leonardiwagner** [comment]
@havid0707 you have to answer the manual check: https://github.com/linkedtales/scrapedin/wiki/Tips

It's a requirement from LinkedIn when you use another IP proxy, then it'll work! :smile:

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
