### ISSUE TITLE
LinkedIn website changed and scrapedin can't read basic data.

### ISSUE THREAD

**Issue by khaledhesham2017** [linkedtales/scrapedin#64]
I want to get cv from "about section", so I change the template but I have this error LinkedIn website changed and scrapedin can't read basic data.

**Comment by leonardiwagner** [comment]
@khaledhesham2017 you broke the template. If any data is collected from the template it'll throw that message. Please post here your template.

**Comment by khaledhesham2017** [comment]
yes, I need to edit the template to get cv from about section. how can make it?

**Comment by leonardiwagner** [comment]
@khaledhesham2017 please post here your template, so I can help tell you what's wrong.

**Comment by khaledhesham2017** [comment]
aboutAlternative: {
    selector: '.pv-about-section',
    fields: {
      text: 'p'
      cv:'div'
    }
  }

**Comment by leonardiwagner** [comment]
@khaledhesham2017 print the `rawProfile` as `console.log(JSON.stringify(rawProfile, undefined, 2))` before the [line #76 on profile.js](https://github.com/linkedtales/scrapedin/blob/master/src/profile/profile.js#L76) and post the full raw profile here.

`aboutAlternative` is only being used if there's no data on `about`, [see here](https://github.com/linkedtales/scrapedin/blob/master/src/profile/cleanProfileData.js#L26)

**Comment by leonardiwagner** [comment]
Closed due to lack of feedback
