### ISSUE TITLE
LinkedIn website changed and scrapedin can't read basic data

### ISSUE THREAD

**Issue by ukshedrack** [linkedtales/scrapedin#66]
I have the code below but having issues making it work. Do I have to clone the repository or something? NB: I also inputed my linkedin password.

var http = require('http');
const scrapedin = require('scrapedin');

// Options object with scrapedin parameters
const options = {
    email: 'ukshedrack@gmail.com',
    password: 'linkedin.password'
}

scrapedin(options)
.then((profileScraper) => profileScraper('https://www.linkedin.com/in/some-profile/'))
.then((profile) => console.log(profile));

var server = http.createServer(function(req, res){
    console.log('request was made: ' + req.url);
    res.end('Hey ninjas');
});

server.listen(3000, '127.0.0.1');
console.log('yo dawgs, now listening to port 3000');

**Comment by ukshedrack** [comment]
This is the error message

(node:21124) UnhandledPromiseRejectionWarning: Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at 
https://github.com/linkedtales/scrapedin/issues
    at module.exports (C:\Users\Ukenazor Shedrack\Desktop\BED\project\node_modules\scrapedin\src\profile\cleanProfileData.js:12:11)
    at module.exports (C:\Users\Ukenazor Shedrack\Desktop\BED\project\node_modules\scrapedin\src\profile\profile.js:76:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
request was made: /
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
yo dawgs, now listening to port 3000
(node:14420) UnhandledPromiseRejectionWarning: Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at 
https://github.com/linkedtales/scrapedin/issues
    at module.exports (C:\Users\Ukenazor Shedrack\Desktop\BED\project\node_modules\scrapedin\src\profile\cleanProfileData.js:12:11)
    at module.exports (C:\Users\Ukenazor Shedrack\Desktop\BED\project\node_modules\scrapedin\src\profile\profile.js:76:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ukshedrack** [comment]
This is the error message

(node:14420) UnhandledPromiseRejectionWarning: Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at 
https://github.com/linkedtales/scrapedin/issues
    at module.exports (C:\Users\Ukenazor Shedrack\Desktop\BED\project\node_modules\scrapedin\src\profile\cleanProfileData.js:12:11)
    at module.exports (C:\Users\Ukenazor Shedrack\Desktop\BED\project\node_modules\scrapedin\src\profile\profile.js:76:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by leonardiwagner** [comment]
Hi @ukshedrack I couldn't reproduce this error, so I have some questions:

- Are you using a recruiter or company account instead of a regular user one?
- Is this error still happening?

**Comment by ukshedrack** [comment]
I am using a regular LinkedIn account (mine). 

Also, the error is still happening.

**Comment by leonardiwagner** [comment]
@ukshedrack please include the following `isHeadless` and `hasToLog` options on scrapedin function, example:

```javascript
scrapedin({
  isHeadless: false,
  hasToLog: true
})
```

In that way, it's possible to see what's happening on the browser, and also please post here the generated log on the console.

Ahh.. use also my profile as test: https://www.linkedin.com/in/leonardiwagner/ 

last but not least , also confirm you are using scrapedin `v1.0.11`.

**Comment by ukshedrack** [comment]
Please by scrapedin function, do you mean scraper.js?

Also where am I suppose to input your profile? Thank you

**Comment by ukshedrack** [comment]
![Screenshot (398)](https://user-images.githubusercontent.com/54557221/74254280-85456100-4cf0-11ea-8bea-f2c2cb600eda.png)

That is what was logged to me.

**Comment by leonardiwagner** [comment]
@ukshedrack  please delete the screenshot it has your password there.

**Comment by ukshedrack** [comment]
Really sorry about that
![Screenshot (399)](https://user-images.githubusercontent.com/54557221/74254640-03096c80-4cf1-11ea-90b5-73b0af115078.png)

**Comment by ukshedrack** [comment]
> @ukshedrack please delete the screenshot it has your password there, and now also change your password.
> 
> If you use this same password for other stuff, you also have to change there as well.

Okay. I will be sure to do that. Thanks for the observation.

**Comment by ukshedrack** [comment]
> Really sorry about that
> ![Screenshot (399)](https://user-images.githubusercontent.com/54557221/74254640-03096c80-4cf1-11ea-90b5-73b0af115078.png)

Is this what I should have?

**Comment by leonardiwagner** [comment]
@ukshedrack yes, where's the error? it seems to be working, right?

**Comment by ukshedrack** [comment]
Yes. It's working now. Thank you so much

**Comment by leonardiwagner** [comment]
@ukshedrack all right, so it worked without doing anything, right? That means LinkedIn really changed something meanwhile and now it came back to "normal". It's not usual, but it may really happen.

It can also change again, so please open another issue if it happens one more time.

Ahh.. and my bad about the password thing, I could also delete the comment as I'm a project owner, I forgot that :hear_no_evil:
