### ISSUE TITLE
Education reported as position

### ISSUE THREAD

**Issue by ephe-meral** [linkedtales/scrapedin#68]
Hi - while testing the scraper, I found a mixup of the data:
Education (i.e. university / degree / field of study) is reported correctly in the education section, but also additionally as a position.
Not sure if thats a feature or a bug, but it seems very weird to have this distinction and then mix it up anyway...

Ex:

```js
  positions: [
    //...
    {
      title: 'Some School',
      companyName: 'Degree Name\nPost Graduate',
      description: 'Some description'
    }
    //...
  ]
  educations: [
    //...
    {
      title: 'Some School',
      degree: 'Post Graduate',
      fieldofstudy: 'Business Administration and Management',
      date1: '2010',
      date2: '2012'
    }
    //...
  ]
```

**Comment by leonardiwagner** [comment]
@ephe-meral Hi, thanks for reporting that, it was a LinkedIn change. I fixed that, please update your scrapedin version to: **1.0.12** 

[changes](https://github.com/linkedtales/scrapedin/pull/69/files)

please confirm if it's working now to you as well, thank you.

**Comment by cyanide2019** [comment]
hi , @ephe-meral  I am also trying to scrape profiles from linkedin , but get the restriction from them about using automated tools,did you get the same thing while you doing this ?

**Comment by ephe-meral** [comment]
@leonardiwagner Sorry for the late reply, and thanks for the quick fix :)
I tested it today and it looks good to me now.

@cyanide2019 I am using the cookies option, but I also didn't scrape too many profiles yet, so I assume this will happen sooner or later anyway - if they detect my profile to do nothing else really.

**Comment by leonardiwagner** [comment]
thank you for the feedback :smile:
