### ISSUE TITLE
Profile picture is not being gathered

### ISSUE THREAD

**Issue by leonardiwagner** [linkedtales/scrapedin#8]
Since it's a background image, it needs to be gathered via JS using page.$eval

**Comment by gigaBITE397** [comment]
Hey @leonardiwagner,

It's not a Background image since we can parse it at below Path

> .pv-top-card-v3--photo .pv-top-card-section__image img

But, I tried getting that image and It returns **null**

**Comment by leonardiwagner** [comment]
solved at #35
