### ISSUE TITLE
Duplicate entries in positions when there are more than one role in the same company

### ISSUE THREAD

**Issue by AdityaAnand1** [linkedtales/scrapedin#80]
How to reproduce: When there are more than roles in a company, scrapedin returns the roles under the position object as well as separately under the root position array. I think the logic for deciphering the roles needs to be updated.

I was able to fix it with the following hack:
```
profile.positions = profile.positions.filter(it =>
        !it.roles || it.roles.length > 1
    )
```

**Comment by leonardiwagner** [comment]
thank you, I added this fix on v`1.0.16` :partying_face:
