### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by neverton1970** [linkedtales/scrapedin#82]
Hi, just before I sit down and try to write my own, has anyone found a way to pass proxy authentication details?

I know in puppeteer to use the page.authentication option, just started reading through the code, but then thought I'd ask on here in case anyone has a way of passing the details through, as the only way I can find is to modify the actual sources within node_modules/scrapedin which means I'll overwrite them if there's an update ...

**Comment by leonardiwagner** [comment]
Hi @neverton1970 ,  I [did an update on scrapedin](https://github.com/linkedtales/scrapedin/commit/df32ab68be687b770cfaf307af0658264454952f) allowing you to use the puppeteer `.athenticate()`

Please update your scrapedin version to v`1.0.13`

To use this feature you have to use the `puppeteerAuthenticate` option on scrapedin, I also placed `puppeteerArgs` as well as example to pass a proxy server:

```js
scrapedin({
  email: 'login@mail.com',
  password: 'pass',
  cookies: {},
  ...,
  puppeteerArgs: [`--proxy-server=0.0.0.0:0000}`],
  ...,
  puppeteerAuthenticate: { username: 'a' , password: 'b' }
})
```

:warning: Important: I didn't test! Please provide some feedback if worked, or a fix :smile: , thank you.

**Comment by neverton1970** [comment]
Hi,
  That's fantastic news :)

  I'll download and try now

  FYI, on a different subject, I've noticed on my testing using puppeteer for a different project that adding a small delay ( say page.waitFor(1000) after doing page.cookies makes a big different. Might get away with a smaller delay, I've not had chance to test yet.

Regards

**Comment by neverton1970** [comment]
Hi,
  Just done a couple of runs, worked perfectly for those 2, will keep you informed if I get any issues.

  Many thanks for sorting this, I owe you a few drinks :)

 By the way, works OK with the cookies without any delays, if I come across any issues, I'll add the delay, see if it resolves the issue and let you know

Regards

**Comment by leonardiwagner** [comment]
Thank you for your feedback @neverton1970 ! I will also consider the delay thing after cookies, we have some reports and this may help us! :smile: feel free to report any issues you found, thanks!
