### ISSUE TITLE
Possible addition to scraper

### ISSUE THREAD

**Issue by neverton1970** [linkedtales/scrapedin#85]
Hi,
  I've been looking for a way to add the company information to each profile scraped, but I've been struggling to add the follow through ( click on each Company, click on About etc.

  So I've done the following, not sure if it helps anyone

Changed the profileScraperTemplate.js to the following **bold** section ;
  positions: {
    selector: 'section[id=experience-section] li',
    fields: {
      title: 'h3',
      **companyURL: {
        selector: 'a',
        attribute: 'href'
      },**
      companyName: '.pv-entity__secondary-title',
      location: '.pv-entity__location span:last-child',
      description: '.pv-entity__description',
      date1: '.pv-entity__date-range span:last-child',
      date2: '.pv-entity__bullet-item-v2',
      roles: {
        selector: '.pv-entity__role-details',
        hasChildrenFields: true,
        fields: {
          title: 'h3 span:last-child',
          description: '.pv-entity__description',
          date1: '.pv-entity__date-range span:last-child',
          date2: '.pv-entity__bullet-item-v2',
          location: '.pv-entity__location span:last-child'
        }
      }
    }
  },

then to get the company details, go to companyURL/about and read the required fields from there. Bit of a fudge, but ideal for anyone wanting company information :)

You won't always get a company URL, sometimes you'll get a search phrase, but a simple indexOf("/company/") will tell you if it's a valid company link

**Comment by leonardiwagner** [comment]
oh, thank you @neverton1970 , I'll include in the project for sure, [you can send code via Pull Requests](https://opensource.com/article/19/7/create-pull-request-github) and send it by yourself as well if you want. :smile:

**Comment by leonardiwagner** [comment]
added on recently published v`1.0.15`, thank you.
