### ISSUE TITLE
Cannot read property 'newPage' of undefined

### ISSUE THREAD

**Issue by karanrajpal14** [linkedtales/scrapedin#86]
Hello,

I've been trying to get this to work but I'm unable to. I'm just following along the getting started tutorial and attempting to scrape my own page like so:

```js
const scrapedin = require('scrapedin')

const options = {
    email: <email>,
    password: <pass>,
}

scrapedin(options)
    .then((profileScraper) => profileScraper('https://www.linkedin.com/in/karan-rajpal/'))
    .then((profile) => console.log(profile))
    .catch(e => console.log(e))
```

But I get the following error:

```bash
➜ node index.js
TypeError: Cannot read property 'newPage' of undefined
    at module.exports (/mnt/d/projects/email-automation-node/node_modules/scrapedin/src/openPage.js:14:30)
    at module.exports (/mnt/d/projects/email-automation-node/node_modules/scrapedin/src/login.js:6:22)
    at module.exports (/mnt/d/projects/email-automation-node/node_modules/scrapedin/src/scrapedin.js:21:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any idea what's going wrong? Am I doing something wrong?

**Comment by neverton1970** [comment]
Hi,  I've just had this, then changed the login to use proxyauthentication and cookies and it's working again.

**Comment by neverton1970** [comment]
Hi,
  Just tried it again, I'm getting the error if I try to login with username/password, but if I use cookies it works fine.

**Comment by leonardiwagner** [comment]
Hi @karanrajpal14  and @neverton1970 it was a bug on v`1.0.13`, [I fixed that](https://github.com/linkedtales/scrapedin/commit/d9477b3e45107c4136805ccbec7f12ef33a0b1d3)

Please try again using v`1.0.14` and provide feedback if it's working now, thanks!

**Comment by neverton1970** [comment]
Hi, that's working for me, many thanks for the quick reply and fix :)

**Comment by leonardiwagner** [comment]
thanks for the feedback!

**Comment by karanrajpal14** [comment]
Yes the issue is fixed now. Thank you!
