### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by acanimal** [linkedtales/scrapedin#91]
Hi,
for some profiles I'm getting the next error:

```
TypeError: Cannot read property 'replace' of undefined
    at module.exports (/..../scrapedin/src/profile/cleanProfileData.js:55:81)
```

any help?
thanks

**Comment by raphaelpreston** [comment]
Seconded. I thought maybe this was unique to me since I've had to use @mNpenner's [creative fix](https://github.com/puppeteer/puppeteer/issues/1837#issuecomment-522850970) to get the puppeteer dependency to work in the first place.

```javascript
const scrapedin = require('scrapedin')
const fs = require('fs')
const rimraf = require('del');

const PATHS = {
    win32: {
        executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        userDataDir: 'C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\puppeteer_user_data',
    },
    linux: {
        executablePath: "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe",
        userDataDir: '/mnt/c/Users/<USERNAME>/AppData/Local/Temp/puppeteer_user_data',
    },
}

const cookies = fs.readFileSync('secure/linkedin.cookie')
const options = {
  cookies: JSON.parse(cookies),
  puppeteerArgs: {
    executablePath: PATHS[process.platform].executablePath,
    userDataDir: PATHS.win32.userDataDir,
    headless: false,
  }
}

scrapedin(options)
.then((profileScraper) => profileScraper('https://www.linkedin.com/in/raphaelpreston/'))
.then((profile) => console.log(profile))
.finally(async () => {
    rimraf(PATHS[process.platform].userDataDir, {force: true}).then(() => {
        console.log("Deleted")
    })
}).catch(err => {
    console.error(err);
    process.exit(1);
});
```

**Comment by kf6kjg** [comment]
Both #89 and #90 contain fixes for this.

**Comment by raphaelpreston** [comment]
Will those be pulled into master any time soon do you think?

**Comment by leonardiwagner** [comment]
added on recently published v`1.0.15`, thank you all.

**Comment by leonardiwagner** [comment]
@kf6kjg now you have permission to write in this repository, feel free to answer issues, send and merge pull requests, and etc..like in any of your created repo,  this project isn't "mine" at all it's ours, I don't earn a penny from it :smile:  , I'm just here helping each other as we do.

the only thing that will be "mine" is publishing new versions to npm, so I'll checking the merged PRs to publish new versions, feel free to contact me on e-mail as well, thanks! :+1:

**Comment by raphaelpreston** [comment]
After updating to `1.0.16`, most profiles that I encountered that were previously throwing this error were fixed, but it's still throwing for at least one profile. I'd show the profile if not for the privacy concernts. If it helps, we are connections on LinkedIn.

My code: 
```javascript
const cookies = fs.readFileSync('secure/linkedincookie.json')
const options = {
...
}

const PROFILE= 'https://www.linkedin.com/in/**********'

scrapedin(options)
.then((profileScraper) => profileScraper(PROFILE))
.then((profile) => console.log(JSON.stringify(profile, null, 2)))
.catch(err => {
    console.error(err);
    process.exit(1);
})
```

Error output: 
```
TypeError: Cannot read property 'replace' of undefined
    at <DIR>/scrapedin/src/profile/cleanProfileData.js:84:18
    at Array.map (<anonymous>)
    at module.exports (<DIR>/scrapedin/src/profile/cleanProfileData.js:82:39)
    at module.exports (<DIR>/scrapedin/src/profile/profile.js:82:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by kf6kjg** [comment]
Good catch. I'll see if I can do a review for any more of these data-existence assumptions: just glancing over that file this morning I found 3 possible points of failure.

**Comment by kf6kjg** [comment]
@raphaelpreston I've pushed a fix to master that should cover the remaining places that problem could pop up.  Could you give it a whirl and let us know the results?

**Comment by raphaelpreston** [comment]
Amazing. Pulled from GitHub and it officially works! Thanks a bunch.

**Comment by kf6kjg** [comment]
@leonardiwagner When you can, please review the changes and release. This problem is should now be fully fixed.
