### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by gautierdag** [linkedtales/scrapedin#96]
I am running into a problem where a profile I would like to scrape has an `undefined` for the `year` field in their `profile.courses`. 

This breaks in `/src/profile/cleanProfileData.js`  since the library tries to call `.replace` on an `undefined`. 

I can make a PR to fix this particular issue, but maybe there are other attributes that can potentially be undefined. It might be better to not ever call `replace` on potentially undefined fields before checking for `undefined`. 

I haven't tested if this can occur in other attributes but it might be highly likely.

**Comment by anibal-aguila** [comment]
**same here**

**Comment by gautierdag** [comment]
Just realised this was fixed in https://github.com/linkedtales/scrapedin/pull/93. I'll close this and use the master branch instead of the `npm` package.
