### ISSUE TITLE
Recommendations fields empty

### ISSUE THREAD

**Issue by Laura2797** [linkedtales/scrapedin#99]
Hi, I'm using the tool on a profile with recommendations and it doesn't fill anything in its specific fields.

recommendations: {
    givenCount: undefined,
    receivedCount: undefined,
    given: [],
    received: []
  },

**Comment by leonardiwagner** [comment]
fixed at version `v1.0.17` , please update your scrapedin version and give us feedback, thanks!

**Comment by Laura2797** [comment]
> fixed at version `v1.0.17` , please update your scrapedin version and give us feedback, thanks!

Is working now, thank you!!
